from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from .models import BillDetails  # Ensure this matches your actual model name

def print_bill(request, bill_id):
    # Retrieve bill details from the database
    bill = get_object_or_404(BillDetails, pk=bill_id)

    # Create an HTTP response with the PDF content type
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'inline; filename="bill_{bill_id}.pdf"'  # Display in browser, not saved

    # Create a new PDF object
    p = canvas.Canvas(response, pagesize=letter)
    width, height = letter  # Get page width and height

    # Set title
    p.setFont("Times-Bold", 16)
    p.drawString(200, height - 50, "Pharmacy Receipt")

    # Draw receipt details
    p.setFont("Times-Bold", 12)
    y_position = height - 100  # Start position
    line_spacing = 20  # Space between lines

    p.drawString(50, y_position, f"Bill Number: {bill.pk}")
    y_position -= line_spacing
    p.drawString(50, y_position, f"Medicine: {bill.med_id.name}")
    y_position -= line_spacing
    p.drawString(50, y_position, f"Customer: {bill.customer}")
    y_position -= line_spacing
    p.drawString(50, y_position, f"Quantity: {bill.quantity}")
    y_position -= line_spacing
    p.drawString(50, y_position, f"Total Amount:Rs{bill.total_amount()}")
 
    y_position -= line_spacing
    p.drawString(50, y_position, f"Generated by: {bill.generated_by.username} ({bill.generated_by.email})")
    y_position -= line_spacing
    p.drawString(50, y_position, f"Date & Time: {bill.created_on}")

    # Finalize the PDF
    p.showPage()
    p.save()

    return response
