# Generated by Django 4.1.2 on 2025-02-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
