# Generated by Django 4.1.2 on 2025-02-27 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yolo_site', '0002_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdetails',
            name='med_id',
        ),
        migrations.RemoveField(
            model_name='billdetails',
            name='quantity',
        ),
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yolo_site.billdetails')),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_items', to='yolo_site.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='billdetails',
            name='items',
            field=models.ManyToManyField(through='yolo_site.BillItems', to='yolo_site.medicine'),
        ),
    ]
